### ISSUE TITLE
Ensure ordering (`nav_order`) works. Place any pages with nav_order above those without it. 

### ISSUE THREAD

**Issue by SirLich** [Bedrock-OSS/bedrock-wiki-vite#107]
Pages with explicit `nav_order `should always be shown above pages without `nav_order`. Pages with `nav_order` should be sorted by `nav_order`, then alphabetical.

**Comment by SirLich** [comment]
Looks like it works for 1+, but breaks on zero. Can we fix this?

**Comment by sermah** [comment]
*just don't use zero lol*

**Comment by sermah** [comment]
*now zero is legal, use it if you want (but better don't, that's not cool)*
