### ISSUE TITLE
Drop-down CSS (tailwind?)

### ISSUE THREAD

**Issue by SirLich** [Bedrock-OSS/bedrock-wiki-vite#12]
Current drop-down doesn't look amazing. Can we properly implement tailwind classes, to make it match Bedrock.dev?
![image](https://user-images.githubusercontent.com/18729296/118787093-c385e480-b892-11eb-9805-e4b736f8bba5.png)
![image](https://user-images.githubusercontent.com/18729296/118787120-cbde1f80-b892-11eb-9377-c00f7d7eb40e.png)

**Comment by solvedDev** [comment]
Adding the JS/Vue tag because I believe we should create our own Vue component for the dropdown

**Comment by solvedDev** [comment]
![image](https://user-images.githubusercontent.com/33347616/119120794-fe238480-ba2c-11eb-919d-12110ae60541.png)
