### ISSUE TITLE
Create/Port contributors widget

### ISSUE THREAD

**Issue by SirLich** [Bedrock-OSS/bedrock-wiki-vite#16]
![image](https://user-images.githubusercontent.com/18729296/118788063-b0274900-b893-11eb-9b85-cf687867fbb6.png)

**Comment by SirLich** [comment]
@stirante I assigned you, since you wrote the original widget.

**Comment by stirante** [comment]
I started implementing it but couldn't finish due to some issues I couldn't resolve with Vue.

https://github.com/Bedrock-OSS/bedrock-wiki-vite/blob/dev/docs/.vitepress/theme/Components/Content/Contributors.vue

**Comment by solvedDev** [comment]
Closed by b3573141a90d38ff27be1fa351ebc2cdaaffd672
