### ISSUE TITLE
Write 404 resolver for redirecting links

### ISSUE THREAD

**Issue by SirLich** [Bedrock-OSS/bedrock-wiki-vite#17]
This can wait until 1.1, since we will be doing a giant reorganization of the content, after the platform is complete.

**Comment by sermah** [comment]
[A guide to create a custom 404 page for github pages](https://docs.github.com/en/pages/getting-started-with-github-pages/creating-a-custom-404-page-for-your-github-pages-site)

**Comment by SirLich** [comment]
This needs to keep as many old links as possible alive, by using js to redirect to a good page. For example:

https://wiki.bedrock.dev/documentation/biome-tags

Needs to become: 

https://wiki.bedrock.dev/world-generation/biome-tags

**Comment by stirante** [comment]
Added a simple resolver to 404 page in https://github.com/Bedrock-OSS/bedrock-wiki-vite/commit/44feaa3b2680b3ec8c2df6294232a006bf93c35b

**Comment by SirLich** [comment]
Closing
