### ISSUE TITLE
Create better styling for light-theme code-blocks

### ISSUE THREAD

**Issue by SirLich** [Bedrock-OSS/bedrock-wiki-vite#20]
Currently, they share a theme:
![image](https://user-images.githubusercontent.com/18729296/118788868-7e62b200-b894-11eb-8526-d0d7d3260b07.png)
![image](https://user-images.githubusercontent.com/18729296/118788878-828ecf80-b894-11eb-9d9e-215199e49400.png)

**Comment by Kas-tle** [comment]
@SirLich 
d353b05 should resolve but please make sure it's to your liking

**Comment by SirLich** [comment]
Looks good enough for a v1.0 release! Resolved!
