### ISSUE TITLE
Backmerge wiki edits from last 2 months.

### ISSUE THREAD

**Issue by SirLich** [Bedrock-OSS/bedrock-wiki-vite#31]
After splitting, pages have been edited, and new pages added. 

Most likely needs to be done by hand, although it won't be too much work because there wasn't that many commits, I think.

**Comment by SirLich** [comment]
@Minetite I assigned you to this one, since you showed interest earlier.

**Comment by Minetite** [comment]
Will do work this weekend!!!

**Comment by SirLich** [comment]
@ThijsHankelMC I did this one 👋
