### ISSUE TITLE
Invalid usage of CodeHeader

### ISSUE THREAD

**Issue by solvedDev** [Bedrock-OSS/bedrock-wiki-vite#32]
**Link:** https://bedrock-oss.github.io/bedrock-wiki-vite/documentation/emojis.html#custom-emoji

![image](https://user-images.githubusercontent.com/33347616/119033914-156f5d00-b9ae-11eb-85ac-334d6c3ffe8a.png)

**Comment by SirLich** [comment]
This actually used to work. Code headers on images: 
![image](https://user-images.githubusercontent.com/18729296/119034722-f1604b80-b9ae-11eb-8c00-0e18abe3b7af.png)

**Comment by solvedDev** [comment]
Yeah, we need to design a different component here then

**Comment by SirLich** [comment]
Fixed. General-case component tracked in #39
