### ISSUE TITLE
Sidebar generation broken

### ISSUE THREAD

**Issue by Joelant05** [Bedrock-OSS/bedrock-wiki-vite#48]
Since the "index.md" files have been removed from each category, the `generateSidebar()` function is no longer pushing categories without this file to the sidebar data.

**Comment by SirLich** [comment]
Ah yikes, thats my fault. 

I don't really want index pages for each category, unless they are clickable from the category itself. See the current wiki `troubleshooting` section, for example, where we provide meta-level information BEFORE going into per-topic troubleshooting.

I guess you could argue thats more confusing however, and we should just put the index page inside the category.

Somehow we need the ability to have per-category meta pages. Not sure whether thats better inside, or outside of the actual category.

**Comment by SirLich** [comment]
@solvedDev You originally didn't want the sidebar categories to have content. Was that cause it was hard/annoying, or because it was confusing?

I'm just trying to think through how it would look with the current setup.

**Comment by solvedDev** [comment]
We can totally do that, my only worry is that interactions (clicks) might be hard to get right because we overload it

**Comment by SirLich** [comment]
Fixed. Please note some additional sidebar issues, as noted.
