### ISSUE TITLE
Top-level categories in sidebar does not appear to have `nav_order`

### ISSUE THREAD

**Issue by SirLich** [Bedrock-OSS/bedrock-wiki-vite#54]

**Comment by BlueFrog130** [comment]
Looking into this... Honestly have no clue what you are looking for with this issue. The only reference to `nav_order` I can find online is in reference to Jekyll, not to VitePress.

Is this still a concern for you?

I could rig up something for the sidebar by reading the Markdown header, which is something I might consider for 1.1 when taking another look at the sidebar.

**Comment by SirLich** [comment]
Fixed.
