### ISSUE TITLE
Add ability to add contributors over frontmatter

### ISSUE THREAD

**Issue by solvedDev** [Bedrock-OSS/bedrock-wiki-vite#59]
The idea here is to have something like the following in the front-matter:
```
contributors
 - github URL
 - github URL
 ```

This should get merged with the build-time contributors, so we can credit people who may have been lost from the git history.

**Comment by sermah** [comment]
Done
You write:
```
mention:
  - username1
  - username2
  - username3
```
You get:
`github_contributors`, `user1`, `user2`, `user3`
