### ISSUE TITLE
Nav Bar

### ISSUE THREAD

**Issue by ModMaker101** [Bedrock-OSS/bedrock-wiki-vite#629]
Issue: When I press the arrow on the doc on the nav bar it doesn't  close

Affected pages: It make the page unorganized and hard to navaigate.

Suggestions:

**Comment by ModMaker101** [comment]
![Screenshot 2023-04-13 110553](https://user-images.githubusercontent.com/119018978/231803044-288746a6-c8b7-4867-87fa-afd60a508595.png)

**Comment by ModMaker101** [comment]
![Screenshot 2023-04-13 110553](https://user-images.githubusercontent.com/119018978/231803044-288746a6-c8b7-4867-87fa-afd60a508595.png)

**Comment by ThomasOrs** [comment]
Are you currently in a doc inside of that category?
You can't shut the category you are currently in most documentation sites

**Comment by ModMaker101** [comment]
no i wasn't

**Comment by QuazChick** [comment]
This can be reproduced by navigating to a page in a section then returning to the home page, which leaves the section you were just in stuck open.
