### ISSUE TITLE
Typo: "Small Up Down"

### ISSUE THREAD

**Issue by phoenixr-codes** [Bedrock-OSS/bedrock-wiki-vite#643]
# Issue
"Small Up Down" does not make much sense. This is probably a typo and "Small Down Arrow" is meant as the name.

# Page

https://wiki.bedrock.dev/concepts/emojis.html#mobile-ios-android

https://github.com/Bedrock-OSS/bedrock-wiki/blob/e409e3d7b9348b6a3cc643f5415b19aed9cbd503/docs/concepts/emojis.md?plain=1#L53

# Suggestions

Turn"Small Up Down" into "Small Down Arrow"

**Comment by ThomasOrs** [comment]
Resolved by #648
