### ISSUE TITLE
Rethink icon badges

### ISSUE THREAD

**Issue by sermah** [Bedrock-OSS/bedrock-wiki-vite#75]
For now, as far as I understood, the icons are:
- Graduate hat = Guide
- Chemistry glass = Recipe
- Warning sign = Experimental
- Left without icons: Beta, New

I think it should be like that:
- Graduate hat = Guide (left as it is)
- Chemistry glass = Experimental
- Warning sign = Beta OR something really unstable and dangerous OR deprecated
- Deprecated also can be represented as a tombstone

Also, I think it would be ok to use whole words for New and Beta, but without colorful badges

**Comment by SirLich** [comment]
Going to add my own descriptions here:

Guide is not only for guide section, but also for each section independently, so for example there is a beginners guide in World Generation, and in Animation Controllers, etc. Its intended as a "first explanation" of a topic, and should probably be read first. 

Recipe (chem glass atm) is a "How to do X" tutorial, such as: How to make wheel-spin animation, how to make entity fly, how to make entity hold item, how to cancel death effect. This is sort of current "Tutorial" section. 

Warning is actually for BOTH beta and Experemental atm. 

> Also, I think it would be ok to use whole words for New and Beta, but without colorful badges

New will go away I think, and beta is included in the warning icon. I just didn't finish grooming pages yet.

**Comment by sermah** [comment]
I think recipe can be change to something like a scroll. So experimental can be a chem glass
![image](https://user-images.githubusercontent.com/40694307/122022734-8ea47900-cdcf-11eb-86b3-875af413c397.png)

**Comment by sermah** [comment]
Haha, I found the pinned message about tailwind icons. I'll search for something interesting

**Comment by sermah** [comment]
For now:
- Graduate hat = guide
- Lightning = recipe, short
- Beaker = experimental, beta, exp, warning

**Comment by SirLich** [comment]
Closing. I think this has been done, right?
