### ISSUE TITLE
How do I get started creating my custom server?

### ISSUE THREAD

**Issue by borgim** [Bedrock-OSS/bedrock-wiki-vite#757]
Hello everyone! I want to create a minigame server to play with some friends and fiends-of-friends.
I know how to setup a default server using the Minecraft Bedrock Server executable, i'm running an instance in a ubuntu server.
But i want to add some features to my server like user registration and login, because i want to track some players points and make it accessible through a website.

I'm sorry if this is a repeated question or if this isn't the ideal place. I'm new here and in this world of minecraft servers.

**Comment by SmokeyStack** [comment]
Hey there, I would recommend reading through this [page](https://wiki.bedrock.dev/servers/server-software.html) and joining their respective community to get started
