### ISSUE TITLE
Update TypeScript doc

### ISSUE THREAD

**Issue by amg-12** [Bedrock-OSS/bedrock-wiki-vite#765]
Since bridge. now has support for TypeScript, this page should be updated with instructions to set up a project.
[/wiki/docs/scripting/typescript.md](https://github.com/Bedrock-OSS/bedrock-wiki/blob/wiki/docs/scripting/typescript.md)

**Comment by SmokeyStack** [comment]
Is there a documentation page from bridge on how to use TypeScript?

**Comment by Xterionix** [comment]
I don't think the wiki should really cover something as specific as that
