### ISSUE TITLE
Add run_command and queue_command

### ISSUE THREAD

**Issue by Xterionix** [Bedrock-OSS/bedrock-wiki-vite#787]
Issue: ^

Page: https://wiki.bedrock.dev/animation-controllers/entity-commands.html

Just a reminder for me to fix unless someone else wants to

**Comment by Xterionix** [comment]
@MedicalJewel105 This is not done. `queue_command` is not experimental. The page does not cover anything about either method and only mentions them by name.

**Comment by QuazChick** [comment]
Queue command examples have been added to https://wiki.bedrock.dev/entities/entity-events in 816d1e9a68c03f4f7d2a511bf7b4acd03401250a

**Comment by Xterionix** [comment]
Having the entity commands page seems a bit extra then no?
