### ISSUE TITLE
Is it possible to translate to other language

### ISSUE THREAD

**Issue by Dr-XYZ** [Bedrock-OSS/bedrock-wiki-vite#850]
Is it possible to translate to [traditional Chinese](https://en.wikipedia.org/wiki/Traditional_Chinese_characters) (unsimplified Hanzi)?

**Comment by SmokeyStack** [comment]
Per the response in https://github.com/Bedrock-OSS/bedrock-wiki/issues/209, we just simply don't have enough people to translate the entire wiki

**Comment by Xterionix** [comment]
Should be closed no?
