### ISSUE TITLE
Inconsistent spelling of dialogue

### ISSUE THREAD

**Issue by QuazChick** [Bedrock-OSS/bedrock-wiki-vite#865]
https://wiki.bedrock.dev/entities/npc-dialogs

- The page switches between the spellings "dialog" and "dialogue".
- Multiple references to a non-existent `/dialog` command.

Ideally, "dialogue" would always have the "ue" at the end to match the spelling of the dialogue command and folder.

**Comment by MedicalJewel105** [comment]
Done.
