### ISSUE TITLE
Content Issue: Biome tags

### ISSUE THREAD

**Issue by Xterionix** [Bedrock-OSS/bedrock-wiki-vite#876]
Issue: Not updated to1.21 or technically 1.20 since that was the last time they added a biome

Page: https://wiki.bedrock.dev/world-generation/biome-tags.html#top

Suggestions: Update

**Comment by MedicalJewel105** [comment]
Done, wait for update today.

**Comment by Xterionix** [comment]
@MedicalJewel105 This is not done either. All you did was change the date. There are still biome tags missing.

**Comment by Xterionix** [comment]
@MedicalJewel105 Why's this closed again; the content hasn't changed?
