### ISSUE TITLE
Make dark theme more visually pleasing

### ISSUE THREAD

**Issue by Dreamedc2015** [Bedrock-OSS/bedrock-wiki-vite#9]
The dark theme seems a bit to contrasty and could do with more matching to the jekyll wiki's dark theme

**Comment by SirLich** [comment]
@solvedDev Theme isn't a perfect match. Tables are one good example:
![image](https://user-images.githubusercontent.com/18729296/119008596-9ae51400-b992-11eb-98ee-a77daa887a94.png)

**Comment by Joelant05** [comment]
I've pushed a change to the table's colors to make them consistent with bedrock.dev

https://github.com/Bedrock-OSS/bedrock-wiki-vite/commit/c212dde4e0a7f05e0aa1cd7869b28b026b4fd5b3

**Comment by solvedDev** [comment]
Looks great 👍

**Comment by solvedDev** [comment]
What are the other changes you have in mind? From my point of view, the issue should have been closed by c212dde4e0a7f05e0aa1cd7869b28b026b4fd5b3

@SirLich @Dreamedc2015

**Comment by solvedDev** [comment]
If we have other things to fix/change, we should probably create more concrete issues for them

**Comment by SirLich** [comment]
Looks good. Agreed on all points. Closing.
