### ISSUE TITLE
Outdated entity properties

### ISSUE THREAD

**Issue by MedicalJewel105** [Bedrock-OSS/bedrock-wiki-vite#936]
Issue:
![image](https://github.com/user-attachments/assets/c11cb098-812c-4ae5-bc2c-6fab590bf318)

Page: https://wiki.bedrock.dev/entities/entity-properties.html

Suggestions: https://learn.microsoft.com/en-us/minecraft/creator/documents/introductiontoentityproperties?view=minecraft-bedrock-stable

**Comment by SmokeyStack** [comment]
Duplicate: https://github.com/Bedrock-OSS/bedrock-wiki/issues/788
