### ISSUE TITLE
Content Issue in JSON UI

### ISSUE THREAD

**Issue by zelisce** [Bedrock-OSS/bedrock-wiki-vite#943]
Issue:
Spelling in JSON-UI

Page:
`json-ui/json-ui-documentation.html`

Suggestions:
> ``Let's look at happens when `anchor_from: center` and `anchor_from: top_left` ``

Should be:
> ``Let's look at happens when `anchor_from: center` and `anchor_to: top_left` ``

**Comment by QuazChick** [comment]
Fixed! 780d7a4
